/*
 * This file is part of DraWall.
 * DraWall is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * DraWall is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU
 * General Public License along with DraWall. If not, see <http://www.gnu.org/licenses/>.
 * © 2012–2014 Nathanaël Jourdane
 * © 2014 Victor Adam
 */

package cc.drawall;

import java.awt.Color;
import java.awt.Rectangle;
import java.awt.geom.AffineTransform;
import java.io.IOException;

public class PSExporter extends Exporter {

	public PSExporter() {
		super("% % m", "% % l", null, "% % % % % % c", "h");
	}

	@Override
	protected AffineTransform writeHeader(final Drawing drawing) throws IOException {
		final Rectangle bounds = drawing.getBounds();
		out.writeBytes("% Lovingly generated by ConVector\n");
		out.writeBytes("/d{load def}bind def/m/moveto d/l/lineto d/c/curveto d");
		out.writeBytes("/h/closepath d/f/fill d/rg/setrgbcolor d\n");
		return new AffineTransform(1, 0, 0, -1, -bounds.x, bounds.height + bounds.y);
	}

	@Override
	protected void writeColor(final Color color) throws IOException {
		final float[] rgb = color.getRGBColorComponents(null);
		writeFormat("f %.3f %.3f %.3f rg%n", rgb[0], rgb[1], rgb[2]);
	}

	@Override
	protected void writeFooter() throws IOException {
		out.writeBytes("f\n");
	}
}
