/*
 * This file is part of DraWall.
 * DraWall is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * DraWall is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU
 * General Public License along with DraWall. If not, see <http://www.gnu.org/licenses/>.
 * © 2012–2014 Nathanaël Jourdane
 * © 2014-2015 Victor Adam
 */

package cc.drawall.ps;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import cc.drawall.Exporter;

/** Outputs a vector as a PDF. */
public class PDFExporter extends Exporter {

	private final List<Integer> xref = new ArrayList<>(4);

	/** Constructor. */
	public PDFExporter() {
		super(REVERSE, "% % m", "% % l", "", "% % % % % % c", "h");
	}

	@Override
	protected void writeHeader(final double width, final double height, final double ratio) {
		write("%%PDF-1\n");
		write("%% Painstakingly generated by ConVector\n");
		writeObj("<</Pages 1 0 R/Kids[2 0 R]/Count 1>>endobj");
		writeObj("<</Contents 3 0 R/MediaBox[0 0 %.3f %.3f]>>endobj", width, height);
		writeObj("<</Length 4 0 R>>stream");
		write("%f 0 0 %f 0 0 cm\n", ratio, ratio);
	}

	@Override
	protected void writeColor(final Color color) {
		final float[] rgb = color.getRGBColorComponents(null);
		write("h f %.3f %.3f %.3f rg\n", rgb[0], rgb[1], rgb[2]);
	}

	@Override
	protected void writeFooter() {
		write("f endstream\nendobj\n");
		writeObj(" %d endobj", bytesWritten() - xref.get(2) - 48);
		final int startxref = bytesWritten();
		write("xref\n1 " + xref.size() + "\n");
		for (final int pos: xref) {
			write("%010d 00000  n\n", pos);
		}
		write("trailer<</Size %d/Root 1 0 R>>", xref.size() + 1);
		write("startxref " + startxref + "\n%%%%EOF");
	}

	private void writeObj(final String content, final Object... args) {
		xref.add(bytesWritten());
		write(xref.size() + " 0 obj" + content + '\n', args);
	}
}
